"""Core utilities and base classes for SciGlob library."""

from sciglob.core.base import BaseDevice
from sciglob.core.commands import (
    ALL_COMMANDS,
    AZIMUTH_MOTOR_COMMANDS,
    BOTH_MOTORS_COMMANDS,
    FILTER_WHEEL_1_COMMANDS,
    FILTER_WHEEL_2_COMMANDS,
    FILTER_WHEELS_COMMON_COMMANDS,
    HEAD_SENSOR_COMMANDS,
    SPECTROMETER_1_COMMANDS,
    SPECTROMETER_2_COMMANDS,
    TRACKER_COMMANDS,
    ZENITH_MOTOR_COMMANDS,
    CommandCategory,
    FirmwareCommand,
    get_command,
    list_commands,
    print_command_reference,
)
from sciglob.core.connection import SerialConnection, parse_position_response, parse_response
from sciglob.core.exceptions import (
    CommunicationError,
    ConfigurationError,
    ConnectionError,
    DeviceError,
    FilterWheelError,
    HomingError,
    MotorAlarmError,
    MotorError,
    PositionError,
    RecoveryError,
    SciGlobError,
    SensorError,
    TimeoutError,
    TrackerError,
)
from sciglob.core.protocols import (
    ERROR_MESSAGES,
    MOTOR_ALARM_MESSAGES,
    TIMING_CONFIG,
    CommandProtocol,
    DeviceType,
    ErrorCode,
    MotorAlarmCode,
    SerialConfig,
    get_error_message,
    get_motor_alarm_message,
)
from sciglob.core.utils import (
    calculate_angular_distance,
    dec2hex,
    degrees_to_steps,
    get_checksum,
    hex2dec,
    normalize_azimuth,
    shortest_rotation_path,
    steps_to_degrees,
    validate_angle,
)

__all__ = [
    # Base
    "BaseDevice",
    # Commands
    "FirmwareCommand",
    "CommandCategory",
    "ALL_COMMANDS",
    "HEAD_SENSOR_COMMANDS",
    "FILTER_WHEEL_1_COMMANDS",
    "FILTER_WHEEL_2_COMMANDS",
    "FILTER_WHEELS_COMMON_COMMANDS",
    "TRACKER_COMMANDS",
    "AZIMUTH_MOTOR_COMMANDS",
    "ZENITH_MOTOR_COMMANDS",
    "BOTH_MOTORS_COMMANDS",
    "SPECTROMETER_1_COMMANDS",
    "SPECTROMETER_2_COMMANDS",
    "get_command",
    "list_commands",
    "print_command_reference",
    # Connection
    "SerialConnection",
    "parse_response",
    "parse_position_response",
    # Exceptions
    "SciGlobError",
    "ConnectionError",
    "CommunicationError",
    "DeviceError",
    "TimeoutError",
    "ConfigurationError",
    "TrackerError",
    "MotorError",
    "FilterWheelError",
    "PositionError",
    "HomingError",
    "MotorAlarmError",
    "SensorError",
    "RecoveryError",
    # Protocols
    "DeviceType",
    "ErrorCode",
    "MotorAlarmCode",
    "SerialConfig",
    "CommandProtocol",
    "ERROR_MESSAGES",
    "MOTOR_ALARM_MESSAGES",
    "TIMING_CONFIG",
    "get_error_message",
    "get_motor_alarm_message",
    # Utils
    "degrees_to_steps",
    "steps_to_degrees",
    "validate_angle",
    "normalize_azimuth",
    "calculate_angular_distance",
    "shortest_rotation_path",
    "dec2hex",
    "hex2dec",
    "get_checksum",
]
